### ISSUE TITLE
Automate cross-account association of VPC and hosted zone

### ISSUE THREAD

**Issue by jsf9k** [cisagov/cool-assessment-terraform#23] opened 2020-03-23 16:27 UTC
# 🚀 Feature Proposal

Right now there is [some manual AWS CLI foo](https://github.com/cisagov/cool-assessment-terraform/blob/develop/vpc.tf#L40-L63) that takes place to associate the assessment VPC with the private hosted zone of the Shared Services VPC.  Terraform does not yet support this kind of cross-account association.  We should make use of a module, such as [this one](https://github.com/opetch/terraform-aws-cli-resource) so that association need not take place manually.

## Motivation

We should eschew manual steps, since
* It is difficult to automate a process that has manual steps.
* Manual steps are error-prone.

**Comment by dav3r** [comment] 2020-03-26 13:38
This issue is a duplicate of #7, so I'm closing this one out.

**Closed as completed by dav3r** 2020-03-26 13:38 UTC
